### ISSUE TITLE
パラメータなどを含むリクエストを投げた時に400が返る可能性がある

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/seichi-api-schema#14]
axumが何を返すのかによる

**Comment by KisaragiEffective** [comment]
400

**Comment by Lucky3028** [comment]
明示的に書かなくても400返してくれるんですか？

**Comment by KisaragiEffective** [comment]
`actix-web`しか使ったことがないのでわかりませんが、`axum`がデフォルトでどういう動作をするかに依らず、パラメーターがinvalidなときは400を返すべきです

**Comment by Lucky3028** [comment]
> パラメーターがinvalidなときは400を返すべきです
それはもちろん理解していて、ライブラリが自動で返すものを確認しないとなというTODOとしてこのissueはつくってあります

**Comment by Lucky3028** [comment]
> $ http -f POST http://localhost:3000/p cv@./data.xml
HTTP/1.1 415 Unsupported Media Type
content-length: 54
content-type: text/plain; charset=utf-8
date: Sat, 10 Dec 2022 08:01:16 GMT

> Expected request with `Content-Type: application/json`

**Comment by Lucky3028** [comment]
ヨシ！

**Comment by Lucky3028** [comment]
（ちなみにPOSTしか設定していないエンドポイントにGETをなげたら405が返ってきたので、それも考慮するべき）

**Comment by Lucky3028** [comment]
> $ http http://localhost:3000/aiueo
HTTP/1.1 400 Bad Request
content-length: 46
content-type: text/plain; charset=utf-8
date: Sat, 10 Dec 2022 08:08:12 GMT

> Invalid URL: Cannot parse `"aiueo"` to a `u16`

**Comment by Lucky3028** [comment]
> $ http "http://localhost:3000/q?p=aiueo"
HTTP/1.1 400 Bad Request
content-length: 65
content-type: text/plain; charset=utf-8
date: Sat, 10 Dec 2022 08:11:26 GMT

> Failed to deserialize query string: invalid digit found in string

**Comment by Lucky3028** [comment]
自動的にちゃんとエラーコード返してくれそう

**Comment by Lucky3028** [comment]
ヨシ！
